### ISSUE TITLE
please specify a non-root user as DARC_USER

### ISSUE THREAD

**Issue by hexclann** [JarryShaw/darc#109]
**Describe the bug**
Unable to run tool: darc -h will result in:
please specify a non-root user as DARC_USER

**To Reproduce**
Run darc after the installation is don

**Server (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by JarryShaw** [comment]
You need to configure an **environment variable** for `DARC_USER` with a value as the *non*-`root` user to run certain darkweb proxies, c.f., [Configuration](https://jarryshaw.github.io/darc/config.html#envvar-DARC_USER) documentation.
