### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by rcyberswish** [JarryShaw/darc#54]
I know your making changes, but I have tried to build this in Python and the Docker with docker-compose. 

The docker fails because there is no Redis DB, 

![image](https://user-images.githubusercontent.com/83964996/117671324-abb5ae80-b176-11eb-84bd-88538ccdc2c0.png)

`/darc# docker-compose up
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Creating network "darc_darc" with driver "bridge"
Creating loader  ... done
Creating crawler ... done
Attaching to crawler, loader
loader     | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
loader     |   value = redis.set('darc', 1)
crawler    | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
crawler    |   value = redis.set('darc', 1)
loader     | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
loader     |   value = redis.set('darc', 1)
crawler    | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
crawler    |   value = redis.set('darc', 1)
loader     | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
loader     |   value = redis.set('darc', 1)
crawler    | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
crawler    |   value = redis.set('darc', 1)
loader     | /app/darc/db.py:153: RedisCommandFailed: ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
`

**Comment by JarryShaw** [comment]
Please install Redis and configure it in your `docker-compose.yml`; you may refer to `docker-compose.debug.yml` as an example.
