### ISSUE TITLE
Java11 JDK fails

### ISSUE THREAD

**Issue by rcyberswish** [JarryShaw/darc#56]
**Describe the bug**
Java JDK wont install . no longer available through apt-get 

**To Reproduce**
Run any of the dockerfiles or docker-compose 

Build fails -  at line 51 and 52 of docker file. 

when running docker-compose up, you get error about hash mismatch (screenshot 2) 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83964996/117835228-cc990500-b245-11eb-8122-1c41b23d4f36.png)

![image](https://user-images.githubusercontent.com/83964996/117836211-7ed0cc80-b246-11eb-813b-c1d1722ffefb.png)

**Desktop (please complete the following information):**
Ubuntu 20.04

**Comment by rcyberswish** [comment]
> I'm not sure if you be using the latest version of DARC or there be some problem with your upstream. The current supported and latest-available LTS version of JDK 11 is apparently **11.0.11**.
> 
> Should you still encounter this problem, I would highly suggest you use the pre-built Docker image from [GitHub Packages](https://github.com/users/JarryShaw/packages/container/package/darc). Do please select the right tag/version when pulling the image.

Apparently no one else has tried to buid your code. 

I did a fresh pull of your repo. and attempt to build your new released image. instead of marking invalid, try actually running these on a new system. 
![image](https://user-images.githubusercontent.com/83964996/117844058-61ebc780-b24d-11eb-9e94-638b12b92e7a.png)

**Comment by JarryShaw** [comment]
Sincerely sorry but I do not understand the reason why your apt upstream find JDK 11 as version 11.0.4; whilst the actual latest available version is 11.0.11, and it's the exact version required from the apt upstream when building from my development environment, production environment and even GitHub Actions.

As I had mentioned, the simplest solution would be you pulling directly the Docker image from GitHub Packages where I had GitHub Action CI/CD building the latest Docker image of DARC. 

Just select one feasible version there, and start working with DARC. As to deployment and technical issues, you can always refer to the documentation on GitHub Pages.

Much appreciation for your understanding.
